# Entry Motion Automation
# Staggered entry lighting on motion detection
# Each light has independent brightness, color, and timeout
#
# Trigger: Entry motion sensor detects motion
# Condition: After sunset / before sunrise (adapts seasonally)
# Mode: restart (re-trigger resets all timers)
#
# Light schedule:
#   North (white):  75% brightness, 2702K warm, 2 min timeout
#   North_2 (RGB):  100% brightness, blue, 5 min timeout
#   South (white):  100% brightness, 6535K daylight, 10 min timeout
#   South_2 (RGB):  100% brightness, blue, 15 min timeout

id: entry_motion_automation
alias: Entry Motion Automation
description: >-
  Staggered entry lighting on motion detection. Each light has independent
  brightness, color, and timeout.
triggers:
  - trigger: state
    entity_id: binary_sensor.entry_motion_motion_detection
    to: "on"
conditions:
  - condition: sun
    after: sunset
    before: sunrise
actions:
  - parallel:
      # North ceiling - warm white, 75% brightness, 2 min
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_north
            data:
              brightness: 191
              color_temp_kelvin: 2702
          - delay:
              minutes: 2
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_north

      # North ceiling 2 (RGB) - blue, 100% brightness, 5 min
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_north_2
            data:
              brightness: 255
              rgb_color: [0, 0, 255]
              effect: "none"
          - delay:
              minutes: 5
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_north_2

      # South ceiling - daylight white, 100% brightness, 10 min
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_south
            data:
              brightness: 255
              color_temp_kelvin: 6535
          - delay:
              minutes: 10
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_south

      # South ceiling 2 (RGB) - blue, 100% brightness, 15 min
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_south_2
            data:
              brightness: 255
              rgb_color: [0, 0, 255]
              effect: "none"
          - delay:
              minutes: 15
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_south_2
mode: restart
