# Entry Motion Automation
# Triggered by: Fibaro FGMS001 motion sensor
# Condition: Sun below horizon (sunset to sunrise)
# Mode: restart (re-trigger resets all timers)
#
# Staggered lighting pattern:
#   North (color_temp):  50% brightness, warm white, 2 min timeout
#   North Accent (hs):   100% brightness, yellow RGB, 5 min timeout
#   South (color_temp):  100% brightness, warm white, 10 min timeout
#   South Accent (hs):   100% brightness, yellow RGB, 15 min timeout

id: entry_motion_automation
alias: Entry Motion Automation
description: >-
  Staggered entry lighting on motion detection.
  Each light has independent brightness, color, and timeout.

trigger:
  - trigger: state
    entity_id: binary_sensor.entry_motion_motion_detection
    to: "on"

condition:
  - condition: sun
    after: sunset
    before: sunrise

action:
  - parallel:
      # North ceiling - color_temp mode, dim warm white, short timeout
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_north
            data:
              brightness: 128
              color_temp_kelvin: 2702
          - delay:
              minutes: 2
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_north

      # North ceiling accent - hs mode, yellow RGB, medium timeout
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_north_accent
            data:
              brightness: 255
              rgb_color: [255, 255, 0]
              effect: "none"
          - delay:
              minutes: 5
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_north_accent

      # South ceiling - color_temp mode, full warm white, long timeout
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_south
            data:
              brightness: 255
              color_temp_kelvin: 2702
          - delay:
              minutes: 10
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_south

      # South ceiling accent - hs mode, yellow RGB, longest timeout
      - sequence:
          - action: light.turn_on
            target:
              entity_id: light.entry_ceiling_south_accent
            data:
              brightness: 255
              rgb_color: [255, 255, 0]
              effect: "none"
          - delay:
              minutes: 15
          - action: light.turn_off
            target:
              entity_id: light.entry_ceiling_south_accent

mode: restart
